### ISSUE TITLE
是否可以无痛使用redis 3.0?

### ISSUE THREAD

**Issue by lostz** [SinaMSRE/ABTestingGateway#1]
因为前段nginx 会有多台,如果使用单台redis 会有很严重的单点问题,如果引入reids 的ha 方案,又增加整体复杂度,是否可以使用redis 3.0 虽然目前不是那么靠谱

**Comment by BG2BKK** [comment]
您好，我没太看懂您的需求。我想我可以先介绍下ab系统的线上部署方法。
<div align="center"><img src="https://raw.githubusercontent.com/SinaMSRE/ABTestingGateway/master/doc/img/deployment.png"></div>

在线上部署时，灰度系统有两个角色，一个是管理机，用来管理分流策略和运行时策略；另一个是分流功能的机器，即7层服务器。每台7层机器有自己的redis，依靠redis的主从复制机制，7层机器的redis作为管理机redis的从机，可以实现同步策略更新。

请问“前段nginx会有多台”，指的是我上面说的那种情况吗

**Comment by chunshengster** [comment]
其实我们建议将redis部署为主从结构，每一台nginx 7层服务器上的部署一个redis slave，用这样的方式来降低请求redis的延迟以及降低对整体响应延迟的影响

**Comment by lostz** [comment]
ok,我明白了.

在 2015年8月19日 上午10:51，Wang Chunsheng <notifications@github.com>写道：
