### ISSUE TITLE
upstream如何与项目进行关联

### ISSUE THREAD

**Issue by yanchaoguo** [SinaMSRE/ABTestingGateway#9]
A服务器启动灰度系统，B服务器启动‘appServer’ 如果在策略中进行定义，才能分流

**Comment by BG2BKK** [comment]
如果是要分流的话, A服务器作为Proxy server, B服务器作为appServer, 是否还要有一个C 服务器作为另一个分流选择呢?

如果是这样的话, 在A服务器中配置 Upstream B和Upstream C, 配置块里写各自的server 列表. 分流时, proxy_pass到http://B或者http://C就可以了
